website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func
from sqlalchemy import Column, ForeignKey, TIMESTAMP
from sqlalchemy.orm import relationship

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)
    first_name = db.Column(db.String(150), nullable=False)
    
    meals = relationship('UserMeal', back_populates='user')
    
class FoodItem(db.Model):
    __tablename__ = 'food_items'
    
    id = Column(db.Integer, primary_key=True, autoincrement=True)
    food_name = Column(db.String(100), nullable=False)
    calories = Column(db.Integer, nullable=False)
    protein = Column(db.Float)
    carbs = Column(db.Float)
    fat = Column(db.Float)
    
    meals = relationship('UserMeal', back_populates='food_item')
    
class UserMeal(db.Model):
    __tablename__ = 'user_meals'
    
    id = Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = Column(db.Integer, ForeignKey('users.id'))
    food_id = Column(db.Integer, ForeignKey('food_items.id'))
    portion_size = Column(db.Float, nullable=False)
    meal_time = Column(TIMESTAMP, server_default=func.now())
    
    user = relationship('User', back_populates='meals')
    food_item = relationship('FoodItem', back_populates='meals')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from dotenv import load_dotenv, find_dotenv
import os

db = SQLAlchemy()
DB_NAME = "database.db"

load_dotenv()

def create_app():
    app = Flask(__name__)
    SECRET_KEY = os.getenv('SECRET_KEY')
    FOODDATA_API_KEY = os.getenv('FOODDATA_API_KEY')
    app.config['SECRET_KEY'] = SECRET_KEY
    # print(SECRET_KEY)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['FOODDATA_API_KEY'] = FOODDATA_API_KEY
    # print(FOODDATA_API_KEY)
    db.init_app(app)
    
    
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, FoodItem, UserMeal
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    with app.app_context():
        db.create_all()
    
    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import  generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password', category='error')
        else:
            flash('Email does not exist.', category='error')
                
    return render_template("login.html", user = current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Invalid Email Address', category='error')
        elif len(first_name) < 1:
            flash('First Name Field must not be empty', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 8:
            flash('Password must contain at least 8 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='scrypt', salt_length=16))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
            
        
    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from .api_utils import search_food_item, get_nutrient_info
from .models import FoodItem, db
views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template("home.html", user = current_user)

@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        food_name = request.form.get('food_name')
        food_data = search_food_item(food_name)
        
        if food_data:
            fdc_id = food_data['fdcId']
            nutrient_info = get_nutrient_info(fdc_id)
            
            calories = next((n for n in nutrient_info['foodNutrients'] if n['nutrient']['name'] == 'Energy'), None)
            protein = next((n for n in nutrient_info['foodNutrients'] if n['nutrient']['name'] == 'Protein'), None)
            carbs = next((n for n in nutrient_info['foodNutrients'] if n['nutrient']['name'] == 'Carbohydrate, by difference'), None)
            fat = next((n for n in nutrient_info['foodNutrients'] if n['nutrient']['name'] == 'Total lipid (fat)'), None)
            
            new_food = FoodItem(food_name=food_data['description'], 
                                calories=calories['amount'] if calories else None, 
                                protein=protein['amount'] if protein else None, 
                                carbs = carbs['amount'] if carbs else None, 
                                fat=fat['amount'] if fat else None)
            db.session.add(new_food)
            db.session.commit()
            
            flash(f"Food '{food_name}' added successfully!", "success")
        else:
            flash("Food item not found.", "error")
    
    return render_template("search.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class="alert alert-danger alert-dismissable fade show" role="alert"> 
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alert-dismissable fade show" role="alert"> 
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
    {%  endif %}
    {% endwith %}




    <div class="container">
      {% block content %}
      {% endblock %}
    </div>



    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}

<h1 align="center">Foods</h1>
</ul>
<form method="POST">
    <textarea name="test" id="food" class="form-control"></textarea>
    <br />
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Food</button>
    </div>
</form>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/search.html
<form method="POST" action="{{ url_for('views.search') }}">
    <label for="food_name">Food Name:</label>
    <input type="text" id="food_name" name="food_name" required>
    <button type="submit">Search</button>
</form>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="flash {{ category }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endwith %}

website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password">
    </div>
    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}